desc: Simple schema for ODAR compliant dataset listings
extensions:
  - ext.py
type: map
mapping:
  Deprecated:
    type: bool
    required: False
  Name:
    type: str
    required: True
  Description:
    type: str
    required: True
  Documentation:
    type: str
    required: True
  Contact:
    type: str
    required: True
  ManagedBy:
    type: str
    required: False
  UpdateFrequency:
    type: str
    required: True
  Collabs:
    type: map
    required: False
    mapping:
      ASDI:
        type: map
        required: False
        mapping:
          Tags:
            type: seq
            required: False
            sequence:
              - type: str
                func: ext_tags
  Tags:
    type: seq
    required: True
    sequence:
      - type: str
        func: ext_tags
  License:
    type: str
    required: True
  RegistryEntryAdded:
    type: str
    required: True
    pattern: ^\d{4}-\d{2}-\d{2}$
  RegistryEntryLastModified:
    type: str
    required: True
    pattern: ^\d{4}-\d{2}-\d{2}$
  Resources:
    type: seq
    required: True
    sequence:
      - type: any
        required: True
        func: ext_valid_bucket_regions
      - type: map
        mapping:
          Description:
            type: str
            required: True
          ARN:
            type: str
            pattern: ^arn:aws|aws-iso:.+:.*:.*:.+$
          Host:
            type: str
            pattern: ^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,63})(\/.*)*\/?$
          Region:
            type: str
            required: True
            pattern: ^.{2}-.+-\d$
          Type:
            type: str
            required: True
            func: ext_resources
          RequesterPays:
            type: bool
          ControlledAccess:
            type: str
            pattern: ^(https?:\/\/)?([\da-z\.\-\_]+)\.([a-z\.]{2,63})(\/.*)*\/?$
            required: False
  DataAtWork:
    type: map
    required: False
    mapping:
      Tutorials:
        type: seq
        sequence:
          - type: map
            mapping:
              Title:
                type: str
                required: True
              URL:
                type: str
                pattern: ^(https?:\/\/)?([\da-z\.\-\_]+)\.([a-z\.]{2,63})(\/.*)*\/?$
                required: True
              AuthorName:
                type: str
                required: True
              AuthorURL:
                type: str
                pattern: ^(https?:\/\/)?([\da-z\.\-\_]+)\.([a-z\.]{2,63})(\/.*)*\/?$
                required: False
              Services:
                type: seq
                required: False
                sequence:
                  - type: str
                    func: ext_services
      Tools & Applications:
        type: seq
        sequence:
          - type: map
            mapping:
              Title:
                type: str
                required: True
              URL:
                type: str
                pattern: ^(https?:\/\/)?([\da-z\.\-\_]+)\.([a-z\.]{2,63})(\/.*)*\/?$
                required: True
              AuthorName:
                type: str
                required: True
              AuthorURL:
                type: str
                pattern: ^(https?:\/\/)?([\da-z\.\-\_]+)\.([a-z\.]{2,63})(\/.*)*\/?$
                required: False
      Publications:
        type: seq
        sequence:
          - type: map
            mapping:
              Title:
                type: str
                required: True
              URL:
                type: str
                pattern: ^(https?:\/\/)?([\da-z\.\-\_]+)\.([a-z\.]{2,63})(\/.*)*\/?$
                required: True
              AuthorName:
                type: str
                required: True
              AuthorURL:
                type: str
                pattern: ^(https?:\/\/)?([\da-z\.\-\_]+)\.([a-z\.]{2,63})(\/.*)*\/?$
                required: False
