desc: Simple schema for ODAR compliant dataset listings
extensions:
  - ext.py
type: map
mapping:
  Deprecated:
    type: bool
    required: False
  Name:
    type: str
    required: True
  Description:
    type: str
    required: True
  Documentation:
    type: str
    required: True
  Contact:
    type: str
    required: True
  ManagedBy:
    type: str
    required: False
  UpdateFrequency:
    type: str
    required: True
  Tags:
    type: seq
    required: True
    sequence:
      - type: str
        func: ext_tags
  License:
    type: str
    required: True
  Resources:
    type: seq
    required: True
    sequence:
      - type: map
        mapping:
          Description:
            type: str
            required: True
          ARN:
            type: str
            pattern: ^arn:aws:.+:.*:.*:.+$
          Host:
            type: str
            pattern: ^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})(\/.*)*\/?$
          Region:
            type: str
            required: True
            pattern: ^.+-.+-.+$
          Type:
            type: str
            required: True
            func: ext_resources
          RequesterPays:
            type: bool
  DataAtWork:
    type: seq
    required: False
    sequence:
      - type: map
        mapping:
          Title:
            type: str
            required: True
          URL:
            type: str
            pattern: ^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})(\/.*)*\/?$
            required: True
          AuthorName:
            type: str
            required: True
          AuthorURL:
            type: str
            pattern: ^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})(\/.*)*\/?$
            required: False